### ISSUE TITLE
Plugin Installation Issue

### ISSUE THREAD

**Issue by opn** [fedwiki/wiki-plugin-transport#2]
Hi would appreciate any advice and help installing plugins on my local server. I'm stuck :)

I can't get the Transport plugin working on localhost. Latest node and npm - fresh install of wiki locally, with github.com/WardCunningham/wiki-plugin-transport

```
Uncaught TypeError: Cannot read property 'emit' of undefined(anonymous function) @ client.js:4m.event.dispatch @ jquery-1.11.3.min.js:4r.handle @ jquery-1.11.3.min.js:4
```

I'm also getting similar errors with About Plugins Plugin. I posted a video and recorded the issue here - http://issues.fedwiki.org/plugin-installation-issues.html

**Comment by paul90** [comment]
Watching the video, you are loading those plugins from github - you should be installing from the NPM package repository. This is because the plugin pushed to github goes not contain any generated javascript. 

An alternative would be to clone the plugin's repository, build it, and install it from that local directory.

You will see that when you when to compile the plugins plugin that it is also missing the client coffeescript, probably because npm is told to ignore those files, so there is nothing there to compile.

I also would not recommend using Node.js v5 (unless you really need it for something else) - there has been little or no testing of our code with that version, and there appears to be some quirks with how npm works.

**Comment by WardCunningham** [comment]
This discussion seems complete.
